export const START_REQUEST = "START_REQUEST";
export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";
export const GET_ONE_STUDENT = "GET_ONE_STUDENT";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const FAILURE_REQUEST = "FAILED_REQUEST";
